"use client";

import Link from "next/link";
import dynamic from "next/dynamic";
import { useEffect, useMemo, useRef, useState } from "react";
import { createClient } from "@/lib/supabase/client";
import { useAuth } from "@/lib/auth-context";
import { businessCategoryLabel, BUSINESS_CATEGORIES } from "@/lib/constants";
import { Spinner } from "@/components/Feedback";
import type { MapMarker } from "@/components/LeafletMap";
import InstallAppButton from "@/components/InstallAppButton";

const LeafletMap = dynamic(() => import("@/components/LeafletMap"), { ssr: false, loading: () => <Spinner label="در حال بارگذاری..." /> });

type Business = { id:string; name:string; category:string; icon:string; image_url:string|null; lat:number|null; lng:number|null; subscription_tier:"bronze"|"silver"|"gold"|null; rating_avg:number; rating_count:number };
type Product = { id:string; business_id:string; name:string; price:number|null; description:string|null; image_url:string|null; discount_percent:number|null };
const CAR_DEALER_CATEGORY = "car_dealer";
const SHOES_BAGS_CATEGORY = "shoes";
const GOLD_PRIORITY_GROUPS: string[][] = [["car_dealer"],["clothing","shoes","cosmetics","jewelry","watch_glasses","mobile","computer","electronics","home_appliances","furniture","supermarket","fruit_store","butcher","bakery","shop"],["real_estate"]];
function goldCategoryPriority(category:string){const idx=GOLD_PRIORITY_GROUPS.findIndex(group=>group.includes(category));return idx===-1?GOLD_PRIORITY_GROUPS.length:idx;}
type Vehicle = { id:string; business_id:string; brand:string; model:string; price:number|null; image_url:string|null; is_sold:boolean };
type FootwearItem = { id:string; business_id:string; brand:string; product_type:string; price:number|null; image_urls:string[]|null; stock_quantity:number|null };
type DisplayProduct = { id:string; name:string; price:number|null; image_url:string|null; discount_percent:number|null };
type CityEvent = { id:string; title:string; category:string|null; event_date:string|null };
const TOROB_RECENT_SEARCHES_KEY="jamcity:torob-recent-searches";
const TOROB_SUGGESTIONS=["گوشی سامسونگ","لپ‌تاپ ایسوس","هدفون بلوتوث","یخچال ساید بای ساید"];
const CATEGORY_PRIORITY=["cafe","restaurant","fitness","car_dealer","repair"];

export default function HomePage(){
 const supabase=useMemo(()=>createClient(),[]); const {user,profile}=useAuth();
 const [businesses,setBusinesses]=useState<Business[]|null>(null); const [products,setProducts]=useState<Product[]>([]); const [activeCategory,setActiveCategory]=useState<string|null>(null);
 const [goldVehicles,setGoldVehicles]=useState<Vehicle[]>([]); const [goldFootwearItems,setGoldFootwearItems]=useState<FootwearItem[]>([]); const [cityEvents,setCityEvents]=useState<CityEvent[]>([]);
 const [torobModalOpen,setTorobModalOpen]=useState(false); const [torobQuery,setTorobQuery]=useState(""); const [torobRecent,setTorobRecent]=useState<string[]>([]); const torobInputRef=useRef<HTMLInputElement>(null);
 const stripDragRef=useRef<{element:HTMLDivElement;pointerId:number;startX:number;startScrollLeft:number}|null>(null);
 function beginStripDrag(event:React.PointerEvent<HTMLDivElement>){if(event.pointerType==="mouse"&&event.button!==0)return;const element=event.currentTarget;element.classList.add("is-manual");element.setPointerCapture(event.pointerId);stripDragRef.current={element,pointerId:event.pointerId,startX:event.clientX,startScrollLeft:element.scrollLeft};}
 function moveStripDrag(event:React.PointerEvent<HTMLDivElement>){const drag=stripDragRef.current;if(!drag||drag.element!==event.currentTarget||drag.pointerId!==event.pointerId)return;event.preventDefault();drag.element.scrollLeft=drag.startScrollLeft-(event.clientX-drag.startX);}
 function endStripDrag(event:React.PointerEvent<HTMLDivElement>){const drag=stripDragRef.current;if(!drag||drag.element!==event.currentTarget||drag.pointerId!==event.pointerId)return;if(drag.element.hasPointerCapture(event.pointerId))drag.element.releasePointerCapture(event.pointerId);drag.element.classList.remove("is-manual");stripDragRef.current=null;}
 function scrollGoldWithWheel(event:React.WheelEvent<HTMLDivElement>){const delta=Math.abs(event.deltaX)>Math.abs(event.deltaY)?event.deltaX:event.deltaY;if(!delta)return;event.preventDefault();event.currentTarget.scrollLeft+=delta;}
 function prepareGoldLoopDrag(event:React.PointerEvent<HTMLDivElement>){beginStripDrag(event);const element=event.currentTarget;const segment=element.scrollWidth/4;if(segment>0&&element.scrollLeft<segment)element.scrollLeft=segment;}
 function keepGoldLoop(event:React.UIEvent<HTMLDivElement>){const element=event.currentTarget;const segment=element.scrollWidth/4;if(segment<=0)return;if(element.scrollLeft<=1)element.scrollLeft=segment+Math.max(0,element.scrollLeft);else if(element.scrollLeft>=segment*2-1)element.scrollLeft=segment+(element.scrollLeft-segment*2);}
 useEffect(()=>{async function loadHome(){const [businessResult,productResult,eventResult]=await Promise.all([supabase.from("businesses").select("id,name,category,icon,image_url,lat,lng,subscription_tier,rating_avg,rating_count").eq("subscription_status","approved"),supabase.from("business_products").select("id,business_id,name,price,description,image_url,discount_percent").order("created_at",{ascending:false}).limit(30),supabase.from("events").select("id,title,category,event_date").eq("is_published",true).order("created_at",{ascending:false}).limit(10)]);const {data:businessData,error:businessError}=businessResult;if(businessError)console.error("Failed to load businesses:",businessError.message);setBusinesses((businessData??[]) as Business[]);const {data:productData,error:productError}=productResult;if(productError)console.error("Failed to load products:",productError.message);setProducts((productData??[]) as Product[]);const {data:eventData,error:eventError}=eventResult;if(eventError)console.error("Failed to load city events:",eventError.message);setCityEvents((eventData??[]) as CityEvent[]);}loadHome();},[supabase]);
 useEffect(()=>{try{const raw=window.localStorage.getItem(TOROB_RECENT_SEARCHES_KEY);if(raw)setTorobRecent(JSON.parse(raw));}catch{}},[]);
 useEffect(()=>{if(!torobModalOpen)return;const timer=window.setTimeout(()=>torobInputRef.current?.focus(),50);function handleKeyDown(e:KeyboardEvent){if(e.key==="Escape")setTorobModalOpen(false);}window.addEventListener("keydown",handleKeyDown);return()=>{window.clearTimeout(timer);window.removeEventListener("keydown",handleKeyDown);};},[torobModalOpen]);
 function openTorobSearch(rawQuery:string){const query=rawQuery.trim();if(!query)return;try{const nextRecent=[query,...torobRecent.filter(item=>item!==query)].slice(0,5);setTorobRecent(nextRecent);window.localStorage.setItem(TOROB_RECENT_SEARCHES_KEY,JSON.stringify(nextRecent));}catch{}window.open(`https://torob.com/search/?query=${encodeURIComponent(query)}`,"_blank","noopener,noreferrer");setTorobModalOpen(false);setTorobQuery("");}
 const visibleBusinesses=useMemo(()=> (businesses??[]).filter(b=>!activeCategory||b.category===activeCategory),[businesses,activeCategory]);
 const markers:MapMarker[]=useMemo(()=>visibleBusinesses.filter(b=>b.lat!==null&&b.lng!==null).map(b=>({id:b.id,lat:b.lat!,lng:b.lng!,title:b.name,subtitle:businessCategoryLabel(b.category),href:`/business/${b.id}`,emoji:b.icon,tier:b.subscription_tier,rating:b.rating_count?b.rating_avg:null})),[visibleBusinesses]);
 const categories=useMemo(()=>{const available=Array.from(new Set((businesses??[]).map(b=>b.category))).map(slug=>BUSINESS_CATEGORIES.find(category=>category.slug===slug)).filter((category):category is NonNullable<typeof category>=>Boolean(category));return available.sort((a,b)=>{const ai=CATEGORY_PRIORITY.indexOf(a.slug),bi=CATEGORY_PRIORITY.indexOf(b.slug);return(ai===-1?999:ai)-(bi===-1?999:bi);});},[businesses]);
 const goldBusinesses=useMemo(()=>[...(businesses??[])].filter(b=>b.subscription_tier==="gold").sort((a,b)=>goldCategoryPriority(a.category)-goldCategoryPriority(b.category)).slice(0,5),[businesses]);
 useEffect(()=>{async function loadGoldSpecialtyProducts(){const goldCarDealerIds=goldBusinesses.filter(b=>b.category===CAR_DEALER_CATEGORY).map(b=>b.id);const goldShoeStoreIds=goldBusinesses.filter(b=>b.category===SHOES_BAGS_CATEGORY).map(b=>b.id);if(goldCarDealerIds.length>0){const {data,error}=await supabase.from("vehicle_listings").select("id,business_id,brand,model,price,image_url,is_sold").in("business_id",goldCarDealerIds).order("created_at",{ascending:false});if(error)console.error("Failed to load gold vehicle listings:",error.message);setGoldVehicles((data??[]) as Vehicle[]);}else setGoldVehicles([]);if(goldShoeStoreIds.length>0){const {data,error}=await supabase.from("footwear_bag_listings").select("id,business_id,brand,product_type,price,image_urls,stock_quantity").in("business_id",goldShoeStoreIds).order("created_at",{ascending:false});if(error)console.error("Failed to load gold footwear/bag listings:",error.message);setGoldFootwearItems((data??[]) as FootwearItem[]);}else setGoldFootwearItems([]);}if(goldBusinesses.length>0)loadGoldSpecialtyProducts();else{setGoldVehicles([]);setGoldFootwearItems([]);}},[supabase,goldBusinesses]);
 const goldProductGroups=useMemo(()=>goldBusinesses.map(business=>{let items:DisplayProduct[];if(business.category===CAR_DEALER_CATEGORY)items=goldVehicles.filter(v=>v.business_id===business.id&&!v.is_sold).map(v=>({id:v.id,name:`${v.brand} ${v.model}`,price:v.price,image_url:v.image_url,discount_percent:null}));else if(business.category===SHOES_BAGS_CATEGORY)items=goldFootwearItems.filter(f=>f.business_id===business.id&&f.stock_quantity!==0).map(f=>({id:f.id,name:`${f.brand} ${f.product_type}`,price:f.price,image_url:f.image_urls?.[0]??null,discount_percent:null}));else items=products.filter(p=>p.business_id===business.id).map(p=>({id:p.id,name:p.name,price:p.price,image_url:p.image_url,discount_percent:p.discount_percent}));return{business,products:items};}).filter(group=>group.products.length>0),[goldBusinesses,products,goldVehicles,goldFootwearItems]);
 const discounts=useMemo(()=>products.filter(p=>(p.discount_percent??0)>0).slice(0,5),[products]);
 const popular=useMemo(()=>[...(businesses??[])].filter(b=>b.rating_count>0).sort((a,b)=>b.rating_avg-a.rating_avg).slice(0,5),[businesses]);
 function findBusiness(id:string){return businesses?.find(b=>b.id===id);} function formatPrice(value:number|null){if(value===null)return"";return `${new Intl.NumberFormat("fa-IR").format(value)} تومان`;}
 return <div dir="rtl" className="home-shell space-y-1 rounded-[30px] pb-8 pt-0 sm:space-y-3 sm:pb-10">
 <InstallAppButton placement="home" />
 <Link href="/news" className="group relative mx-auto -mt-1 flex w-full max-w-md items-center gap-1.5 overflow-hidden rounded-full border border-[#39ff8f]/60 bg-white px-3.5 py-1.5 shadow-[0_0_0_1px_rgba(57,255,143,.15),0_6px_24px_rgba(20,122,75,.12)]"><span className="relative flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#eafff3] text-sm">📰</span><p className="relative hidden shrink-0 text-[11px] font-black text-[#0f9a56] sm:block">اخبار روز</p><div className="relative min-w-0 flex-1 overflow-hidden"><p className="truncate text-[10px] font-bold text-[#3A4A3D]">آخرین اخبار ایران، اقتصاد، جم و عسلویه</p></div><span className="relative shrink-0 rounded-full bg-[#eafff3] px-2.5 py-1 text-[9px] font-black text-[#0f9a56]">همه ←</span></Link>
 {cityEvents.length>0&&<section aria-label="آخرین رویدادهای جم" className="group relative mx-auto -mt-1 flex w-full max-w-[340px] items-center gap-1.5 overflow-hidden rounded-full border border-[#39ff8f]/60 bg-white px-3.5 py-1.5 shadow-sm"><span className="relative flex h-7 w-7 shrink-0 items-center justify-center rounded-full bg-[#eafff3] text-sm">📅</span><div className="relative min-w-0 flex-1 overflow-hidden" dir="rtl"><div className="jam-events-track flex w-max items-center gap-8 whitespace-nowrap">{[...cityEvents,...cityEvents].map((event,index)=><Link key={`${event.id}-${index}`} href={`/events/${event.id}`} className="flex shrink-0 items-center gap-1.5 text-[10px] font-bold text-[#3A4A3D]"><span className="h-1.5 w-1.5 shrink-0 rounded-full bg-[#e2574c]" />{event.title}</Link>)}</div></div><Link href="/events" className="relative shrink-0 rounded-full bg-[#eafff3] px-2.5 py-1 text-[9px] font-black text-[#0f9a56]">همه ←</Link></section>}
 <section className="wall-home-feature relative w-[calc(100%+38px)] -translate-x-[19px] overflow-hidden rounded-[28px] border border-[#f1c1cb] bg-white p-3 shadow-[0_16px_38px_rgba(198,38,76,.12)] sm:p-5"><div className="absolute -left-10 -top-12 h-40 w-40 rounded-full bg-[#ffd9e1]/70 blur-3xl"/><div className="absolute -right-16 -bottom-16 h-48 w-48 rounded-full bg-[#ffe8ae]/55 blur-3xl"/><div className="relative flex flex-row items-start gap-2 sm:items-center sm:justify-between sm:gap-4"><div className="min-w-0 flex-1 flex items-start gap-2 sm:gap-3"><span className="wall-home-feature-icon flex h-11 w-11 shrink-0 items-center justify-center rounded-2xl text-2xl shadow-[0_10px_24px_rgba(198,38,76,.28)] sm:h-16 sm:w-16 sm:text-4xl">💬</span><div><div className="mb-1 flex items-center gap-2"><span className="rounded-full bg-[#c6264c] px-2 py-1 text-[8px] font-black text-white">محور اصلی شهر</span><span className="text-[9px] font-bold text-[#bd6678]">گفتگو، خبر و آگهی‌های محلی</span></div><h2 className="text-lg font-black text-[#351d25] sm:text-2xl">دیوار شهر جم</h2><p className="mt-1 max-w-xl text-[10px] leading-6 text-[#80636b] sm:text-xs">صدای شهروندان جم را ببینید، با همسایه‌ها گفتگو کنید و پیشنهادها و خبرهای مهم شهر را در یک فضای زنده دنبال کنید.</p></div></div><Link href="/wall" className="wall-entry-cta group flex w-auto max-w-[112px] shrink-0 items-center justify-center gap-1 rounded-2xl bg-gradient-to-l from-[#c6264c] to-[#ef476f] px-2 py-2 text-[9px] leading-4 font-black text-white sm:max-w-none sm:gap-2 sm:px-5 sm:py-3 sm:text-xs"><span className="wall-entry-icon">💬</span><span>ورود به دیوار جم</span><span className="text-base">←</span></Link></div></section>
 {goldBusinesses.length>0&&<div className="relative mt-4 overflow-hidden rounded-2xl border border-[#efd49b] bg-gradient-to-l from-[#fff7df] via-white to-[#fffaf0] p-3 sm:p-4"><div className="mb-3 flex items-center justify-between gap-2"><div className="flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-gradient-to-br from-[#ffe29a] to-[#c88b24] text-base">👑</span><div><h3 className="text-[11px] font-black text-[#704817] sm:text-sm">ویترین طلایی کنار دیوار</h3><p className="text-[8px] font-bold text-[#ae8750] sm:text-[9px]">کسب‌وکارها و محصولات منتخب جم</p></div></div><Link href="/businesses" className="rounded-full bg-white px-2.5 py-1.5 text-[8px] font-black text-[#a66b19]">مشاهده همه ←</Link></div><div className="gold-home-viewport min-w-0 flex-1 overflow-x-auto overflow-y-hidden rounded-2xl bg-white/55 px-1 py-1.5" dir="ltr" onPointerDown={prepareGoldLoopDrag} onPointerMove={moveStripDrag} onPointerUp={endStripDrag} onPointerCancel={endStripDrag} onWheel={scrollGoldWithWheel} onScroll={keepGoldLoop}><div className="gold-home-track flex w-max gap-2.5" dir="rtl">{[...goldBusinesses,...goldBusinesses,...goldBusinesses,...goldBusinesses].map((business,index)=>{const group=goldProductGroups.find(item=>item.business.id===business.id);const firstProduct=group?.products[0];return <Link key={`${business.id}-${index}`} href={`/business/${business.id}`} className="priority-gold-card group flex min-w-[190px] shrink-0 items-center gap-2 rounded-2xl border border-[#f0ddb2] bg-white/90 p-2"><div className="relative h-14 w-14 shrink-0 overflow-hidden rounded-2xl border-2 border-[#f0d27f] bg-[#fff6dc]">{business.image_url?<img loading="lazy" decoding="async" src={business.image_url} alt={business.name} className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center text-2xl">{business.icon||"🏪"}</div>}<span className="absolute -bottom-0.5 -left-0.5 text-xs">👑</span></div><div className="min-w-0 flex-1"><p className="truncate text-[10px] font-black">{business.name}</p><p className="mt-1 text-[8px] font-bold text-[#bd8b35]">{business.rating_count>0?`⭐ ${business.rating_avg.toFixed(1)}`:"کسب‌وکار منتخب"}</p>{firstProduct?<p className="mt-1 truncate text-[8px] font-bold text-[#147a4b]">{firstProduct.name}</p>:<p className="mt-1 text-[8px]">مشاهده محصولات ←</p>}</div></Link>})}</div></div></div>}
 <section><div className="mb-3 flex items-center justify-between gap-2 rounded-2xl border border-[#E3EBDE] bg-white px-2.5 py-2 shadow-sm"><span className="shrink-0 text-[9px] font-black text-[#66766A]">دسته‌بندی</span><select value={activeCategory??""} onChange={event=>setActiveCategory(event.target.value||null)} aria-label="فیلتر دسته‌بندی کسب‌وکارها" className="min-w-0 flex-1 appearance-none rounded-xl border border-[#E3EBDE] bg-[#F7F9F4] px-3 py-2 text-right text-[10px] font-bold text-[#3A4A3D]"><option value="">همه کسب‌وکارها</option>{categories.map(c=><option key={c.slug} value={c.slug}>{c.icon} {c.name}</option>)}</select></div><div className="relative isolate z-0 overflow-hidden rounded-[28px] border-4 border-white bg-white shadow-[0_0_0_1px_rgba(57,255,143,.25),0_0_35px_rgba(57,255,143,.18),0_15px_45px_rgba(20,60,40,.1)]">{businesses===null?<div className="flex h-80 items-center justify-center"><Spinner label="در حال بارگذاری نقشه..."/></div>:<LeafletMap markers={markers}/>}</div></section>
 {goldProductGroups.length>0&&<section className="relative overflow-hidden rounded-[24px] border border-[#EFD49B] bg-gradient-to-l from-[#FFF8E6] via-white to-[#FFFCF3] p-3 sm:p-4"><div className="mb-3 flex items-center gap-2"><span className="flex h-8 w-8 items-center justify-center rounded-xl bg-gradient-to-br from-[#FFE29A] to-[#C88B24] text-base">👑</span><div><h2 className="text-[11px] font-black text-[#704817] sm:text-sm">منوی کسب‌وکارهای طلایی</h2><p className="text-[8px] font-bold text-[#AE8750] sm:text-[9px]">محصولات منتخب کسب‌وکارهای ویژه جم</p></div></div><div className="space-y-2.5">{goldProductGroups.map(({business,products:groupProducts})=><div key={business.id} className="flex min-w-0 items-stretch gap-2 rounded-2xl border border-[#F0DDB2] bg-white/70 p-1.5" dir="rtl"><Link href={`/business/${business.id}`} className="flex w-[72px] shrink-0 flex-col items-center justify-center rounded-xl border border-[#F0D27F] bg-gradient-to-b from-[#FFF8DF] to-[#FFF0C4] px-1 py-1.5 text-center"><span className="relative flex h-8 w-8 items-center justify-center overflow-hidden rounded-lg border-2 border-[#F0D27F] bg-white text-base">{business.image_url?<img loading="lazy" decoding="async" src={business.image_url} alt={business.name} className="h-full w-full object-cover"/>:(business.icon||"🏪")}</span><span className="w-full truncate text-[8px] font-black">{business.name}</span><span className="truncate text-[7px] font-bold text-[#BD8B35]">{business.rating_count>0?`⭐ ${business.rating_avg.toFixed(1)}`:"منتخب جم"}</span></Link><div className="gold-products-manual-viewport min-w-0 flex-1 overflow-x-auto overflow-y-hidden rounded-xl bg-white/65 px-1 py-1.5" dir="ltr" onPointerDown={prepareGoldLoopDrag} onPointerMove={moveStripDrag} onPointerUp={endStripDrag} onPointerCancel={endStripDrag} onWheel={scrollGoldWithWheel} onScroll={keepGoldLoop}><div className="flex w-max items-stretch gap-2.5" dir="rtl">{[...groupProducts,...groupProducts,...groupProducts,...groupProducts].map((product,index)=><Link key={`${product.id}-${index}`} href={`/business/${business.id}`} className="group flex w-[172px] shrink-0 items-center gap-2 rounded-xl border border-[#F0DDB2] bg-white p-1.5"><div className="h-11 w-11 shrink-0 overflow-hidden rounded-xl bg-[#FFF6DC]">{product.image_url?<img loading="lazy" decoding="async" src={product.image_url} alt={product.name} className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center text-xl">{business.icon||"🛍️"}</div>}</div><div className="min-w-0 flex-1"><p className="truncate text-[9px] font-black">{product.name}</p>{product.price!==null&&<p className="mt-1 truncate text-[9px] font-black text-[#A66B19]">{formatPrice(product.price)}</p>}<p className="mt-1 text-[8px]">مشاهده ←</p></div></Link>)}</div></div></div>)}</div></section>}
 {discounts.length>0&&<section className="discount-home-showcase relative overflow-hidden rounded-[24px] border border-[#F0D4CE] bg-gradient-to-l from-[#FFF1EE] via-white to-[#FFF9F7] px-3 py-3.5 shadow-sm sm:px-4"><div className="flex items-stretch gap-2.5 pt-1" dir="rtl"><div className="discount-home-label relative z-20 flex w-[92px] shrink-0 flex-col items-center justify-center rounded-2xl border border-[#F0D4CE] bg-gradient-to-b from-[#FFF8F5] to-[#FFE1DC] px-1.5 py-2 text-center sm:w-[126px]"><span className="discount-gift flex h-10 w-10 items-center justify-center rounded-2xl bg-white text-xl">🎁</span><h2 className="mt-1.5 text-[10px] font-black leading-4 text-[#A43E37] sm:text-xs">تخفیف‌های داغ جم</h2><p className="mt-0.5 text-[7px] text-[#B87972] sm:text-[8px]">پیشنهادهای ویژه امروز</p></div><div className="discount-home-viewport min-w-0 flex-1 overflow-x-auto overflow-y-hidden rounded-2xl bg-white/45 px-1 py-1.5" dir="ltr" onPointerDown={beginStripDrag} onPointerMove={moveStripDrag} onPointerUp={endStripDrag} onPointerCancel={endStripDrag} onWheel={scrollGoldWithWheel}><div className="discount-home-track flex w-max items-stretch gap-2.5" dir="rtl">{[...discounts,...discounts,...discounts,...discounts].map((product,index)=>{const business=findBusiness(product.business_id);if(!business)return null;const finalPrice=product.price!==null?Math.round(product.price*(1-(product.discount_percent??0)/100)):null;return <Link key={`${product.id}-${index}`} href={`/business/${business.id}`} dir="rtl" className="discount-home-card group flex w-[190px] shrink-0 items-center gap-2 rounded-2xl border border-[#F0D4CE] bg-white p-2"><div className="relative h-14 w-14 shrink-0 overflow-hidden rounded-xl bg-[#FFF1EE]">{product.image_url?<img loading="lazy" decoding="async" src={product.image_url} alt={product.name} className="h-full w-full object-cover"/>:<div className="flex h-full w-full items-center justify-center text-2xl">🔥</div>}<span className="absolute left-1 top-1 rounded-full bg-[#E2574C] px-1.5 py-0.5 text-[7px] font-black text-white">{product.discount_percent}%</span></div><div className="min-w-0 flex-1"><h3 className="truncate text-[9px] font-black">{product.name}</h3><p className="mt-1 truncate text-[8px]">{business.name}</p>{finalPrice!==null&&<p className="mt-1 truncate text-[9px] font-black text-[#E2574C]">{formatPrice(finalPrice)}</p>}</div></Link>})}</div></div></div></section>}
 {popular.length>0&&<section className="overflow-hidden rounded-[26px] border border-[#E3EBDE] bg-white p-3 shadow-sm sm:p-4"><div className="flex items-center gap-3"><div className="flex w-[92px] shrink-0 flex-col items-center justify-center gap-1 border-l border-[#E3EBDE] pl-3 text-center sm:w-[120px]"><span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#FBEEDA] text-lg">⭐</span><h2 className="text-[11px] font-black text-[#1D2B1F] sm:text-sm">محبوب‌های جم</h2></div><div className="jam-popular-viewport min-w-0 flex-1 overflow-x-auto overflow-y-hidden" dir="ltr" onPointerDown={beginStripDrag} onPointerMove={moveStripDrag} onPointerUp={endStripDrag} onPointerCancel={endStripDrag}><div className="jam-popular-track flex w-max items-stretch gap-2 py-1">{[...popular,...popular,...popular].map((b,index)=><Link key={`${b.id}-${index}`} href={`/business/${b.id}`} dir="rtl" className="flex w-[190px] shrink-0 items-center gap-2 rounded-2xl border border-[#E3EBDE] bg-[#FFFEFC] p-2"><span className="flex h-9 w-9 shrink-0 items-center justify-center rounded-xl bg-[#F3FAF5] text-lg">{b.icon}</span><span className="min-w-0 flex-1"><span className="block truncate text-[9px] font-black">{b.name}</span><span className="mt-1 block truncate text-[8px]">{businessCategoryLabel(b.category)}</span></span><span className="shrink-0 text-[8px] font-black text-[#D98F2B]">⭐ {b.rating_avg.toFixed(1)}</span></Link>)}</div></div></div></section>}
 <section className="relative overflow-hidden rounded-[28px] border border-[#CFE6D6] bg-gradient-to-l from-[#EAF7EE] to-[#F7F9F4] p-3.5 sm:p-8"><div className="relative flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between sm:gap-5"><div><h2 className="text-xl font-black text-[#1D2B1F] sm:text-2xl">حرفی داری؟ <span className="text-[#147A4B]">بیا توی جم بگو.</span></h2><p className="mt-2 text-[10px] text-[#66766A]">با همشهری‌ها صحبت کن، آگهی بگذار و از اتفاقات شهر باخبر شو.</p></div><Link href="/wall" className="rounded-2xl bg-[#0f9a56] px-4 py-2.5 text-center text-[10px] font-black text-white">💬 ورود به دیوار جم</Link></div></section>
 <section className="grid grid-cols-3 gap-1.5 sm:gap-3"><Stat icon="🏪" iconBg="#E3F3E9" value={businesses?.length??0} text="کسب‌وکار"/><Stat icon="👑" iconBg="#FBEEDA" value={goldBusinesses.length} text="طلایی"/><Stat icon="🎁" iconBg="#FCE7E4" value={discounts.length} text="تخفیف فعال"/></section>
 {user&&<section className="text-center"><p className="text-[9px] text-[#8A968C]">خوش آمدی {profile?.display_name||"همشهری"} 🌿</p></section>}
 {torobModalOpen&&<div className="fixed inset-0 z-50 flex items-end justify-center bg-[#1D2B1F]/40 backdrop-blur-sm sm:items-center" onClick={()=>setTorobModalOpen(false)}><div role="dialog" aria-modal="true" onClick={e=>e.stopPropagation()} className="relative w-full max-w-md overflow-hidden rounded-t-[28px] border border-[#F0DCB4] bg-white p-5 shadow-2xl sm:rounded-[28px] sm:p-6"><div className="flex items-center justify-between"><h2 className="text-sm font-black text-[#1D2B1F]">خرید با کف قیمت بازار</h2><button type="button" onClick={()=>setTorobModalOpen(false)} className="rounded-full bg-[#F3F6F1] px-3 py-1.5 text-[9px]">✕</button></div><form onSubmit={e=>{e.preventDefault();openTorobSearch(torobQuery);}} className="mt-4"><input ref={torobInputRef} value={torobQuery} onChange={e=>setTorobQuery(e.target.value)} placeholder="مثلاً گوشی سامسونگ" className="w-full rounded-2xl border border-[#E3EBDE] bg-[#F7F9F4] px-4 py-3 text-xs outline-none"/><button type="submit" className="mt-3 w-full rounded-2xl bg-[#D98F2B] px-4 py-3 text-xs font-black text-white">جستجو در ترب ←</button></form>{torobRecent.length>0&&<div className="mt-4 flex flex-wrap gap-1.5">{torobRecent.map(item=><button key={item} type="button" onClick={()=>openTorobSearch(item)} className="rounded-full border px-3 py-1.5 text-[9px]">{item}</button>)}</div>}<div className="mt-4 flex flex-wrap gap-1.5">{TOROB_SUGGESTIONS.map(item=><button key={item} type="button" onClick={()=>openTorobSearch(item)} className="rounded-full border px-3 py-1.5 text-[9px]">{item}</button>)}</div></div></div>}
 </div>;
}
function Stat({icon,iconBg,value,text}:{icon:string;iconBg:string;value:number;text:string}){return <div className="flex items-center justify-center gap-1.5 rounded-2xl border border-[#E3EBDE] bg-white p-2.5 sm:gap-2.5 sm:p-4"><span className="flex h-8 w-8 items-center justify-center rounded-xl text-base sm:h-9 sm:w-9 sm:text-lg" style={{backgroundColor:iconBg}}>{icon}</span><span><strong className="block text-sm font-black text-[#1D2B1F]">{new Intl.NumberFormat("fa-IR").format(value)}</strong><small className="text-[8px] text-[#8A968C]">{text}</small></span></div>}
